### PR TITLE
MRNN30/31 - [refac] initial seeds to be useful

### PR DESCRIPTION
**Pull request by zach-bob**
This PR allows for the initial seeds to be useful per this [Jira ticket](https://mojotech.atlassian.net/jira/software/projects/MRNN/boards/22?selectedIssue=MRNN-31). When the new production environment is created, this will allow for less  manual configuration.

### CODE REVIEW

**Review by chewnoill — APPROVED** [review]
When do initial seeds run?

**Comment by zach-bob** [comment]
> When do initial seeds run?

Right after a new instance is deployed to the fly.io I think. The last time I spun up the new prod env, I think I had to run them manually though.

**Comment by chewnoill** [comment]
How do you run things manually on fly.io?

**Comment by zach-bob** [comment]
> How do you run things manually on fly.io?

I wish I took better notes when I went through this because it was a mess.

I just found [these docs](https://fly.io/docs/reference/configuration/#builder) on specifying a builder section in `fly.toml` and there is also a target Dockerfile specification here. I think the seeds should be run from here somehow so that way they're automatic.

**Comment by zach-bob** [comment]
[This](https://community.fly.io/t/how-to-run-seeds-exs-for-elixir-phoenix-app/3591/2) is how I ran seeds previously. Since we only need to do it once, this worked fine.

**Pull request merged**
